name: Build Portable EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore "IPSW to iBoot.csproj"

    - name: Build with MSBuild
      run: msbuild "IPSW to iBoot.csproj" /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IPSW-to-iBoot-Portable
        path: ./publish/
